/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as interfaces from "./interfaces";
export type { interfaces };
export type { Attester } from "./Attester";
export type { AttesterResolver } from "./AttesterResolver";
export type { WorldIdVerifier } from "./WorldIdVerifier";
