/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as resolver from "./resolver";
export type { resolver };
export type { IEAS } from "./IEAS";
export type { ISchemaRegistry } from "./ISchemaRegistry";
export type { ISemver } from "./ISemver";
export type { Semver } from "./Semver";
