/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ISchemaResolver } from "./ISchemaResolver";
export type { SchemaResolver } from "./SchemaResolver";
